#!/sbin/tini /bin/ash

export SCW_ACCESS_KEY=$ACCESS_KEY
export SCW_SECRET_KEY=$SECRET_KEY
export SCW_DEFAULT_ORGANIZATION_ID=$DEFAULT_ORGANIZATION_ID
export SCW_DEFAULT_PROJECT_ID=$DEFAULT_PROJECT_ID
export SCW_DEFAULT_ZONE=$DEFAULT_ZONE
export SCW_DEFAULT_REGION=$DEFAULT_REGION

/usr/bin/python3 /app/serve.py 
